### PR TITLE
Log stdout on run command errors

### LINKED ISSUE #238: lerna run swallows errors
this is similar to #119 but larger: the issue seems to include other commands as well.

`lerna run task` only gives me the exit code and swallows all logging the task may have given, which usually includes the compiler error message.

here's the output from `lerna tun ts`:

```
Lerna v2.0.0-beta.13
Independent Versioning Mode
Errored while running npm script 'ts' in '@elements/blueprint'
Error: Command failed: /bin/sh -c npm run ts

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "ts"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @elements/blueprint@2.29.0 ts: `tsc --project .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @elements/blueprint@2.29.0 ts script 'tsc --project .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @elements/blueprint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --project .
npm ERR! You can get their info via:
npm ERR!     npm owner ls @elements/blueprint
npm ERR! There is likely additional logging output above.
```

and here's the output from running the first lerna task directly in its project directory:

```
> @elements/blueprint@2.29.0 ts /Users/ggray/palantir/blueprint/packages/blueprint
> tsc --project .

error TS6053: File 'src/generated/iconClasses.ts' not found.
error TS6053: File 'src/generated/iconStrings.ts' not found.

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "ts"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @elements/blueprint@2.29.0 ts: `tsc --project .`
npm ERR! Exit status 2
```

i've noticed other similar discrepancies between the logging during a `lerna run *` versus during a direct `npm run *` in the project, where lerna gives much less information. perhaps there's an extended buffer on the logger?

### PR DESCRIPTION
**Pull request by rygine**
fixes #238

### CODE REVIEW

File: src/commands/RunCommand.js [hunk 1]
```diff
@@ -56,9 +56,8 @@ export default class RunCommand extends Command {
     NpmUtilities.runScriptInDir(this.script, this.args, pkg.location, (err, stdout) => {
       if (err) {
         this.logger.error(`Errored while running npm script '${this.script}' in '${pkg.name}'`, err);
-      } else {
-        this.logger.info(stdout);
       }
+      this.logger.info(stdout);
```
Comment (gigabo) [inline src/commands/RunCommand.js]: Maybe better to put the output from `stdout` _before_ the error output, so that the errors are more likely to remain on-screen after exit?

Comment (rygine) [inline src/commands/RunCommand.js]: yep

**Comment by gigabo** [comment]
Thanks for this, @rygine. 👍

**Comment by doug-wade** [comment]
👍  this would be great

**Comment by gigabo** [comment]
@thejameskyle, @hzoo - This LGTM.  Mind if I merge?

**Comment by hzoo** [comment]
Yeah 👍

**Comment by kevnk** [comment]
I'm using lerna to run npm scripts that are watching files for change — it works as expected; it just doesn't output anything... This issue seems to only address output on errors though. Is there a `verbose` mode I'm unaware of?

**Comment by gigabo** [comment]
@kevnk - `lerna run` actually buffers all output from each script internally until the script completes, so it won't output anything for you currently.  #278 is related to this, though the `watch` case is a wrinkle that I don't think has been brought up there.  Seems like we're going to at least need the _option_ to disable the buffering and allow output to be interleaved, maybe with a package-name prefix.

**Comment by kevnk** [comment]
Thanks for the info @gigabo!
