### PR TITLE
fix(utils): Use safe relative path when calling git diff

### LINKED ISSUE #1322: Lerna updated not working when a package is in the lerna root dir
## Expected Behavior

When having packages in lerna.json configured as:

`packages: ['packages/*', '.']`

I expect to be able to run `lerna updated` and get list of updated packages.

## Current Behavior
I am getting 

`
$ lerna updated
lerna info version 3.0.0-beta.2
lerna info Checking for updated packages...
lerna info Comparing with v1.0.0.
lerna ERR! Error: Command failed: git diff --name-only v1.0.0 --
lerna ERR! fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
lerna ERR!
lerna ERR!
lerna ERR!     at makeError (/Users/ovca/Code/GitHub/lerna/node_modules/execa/index.js:169:9)
lerna ERR!     at Function.module.exports.sync (/Users/ovca/Code/GitHub/lerna/node_modules/execa/index.js:338:15)
lerna ERR!     at Object.execSync (/Users/ovca/Code/GitHub/lerna/core/child-process/index.js:22:16)
lerna ERR!     at Object.diffSinceIn (/Users/ovca/Code/GitHub/lerna/core/git-utils/index.js:141:38)
lerna ERR!     at hasDiffSinceThatIsntIgnored (/Users/ovca/Code/GitHub/lerna/utils/collect-updates/lib/make-diff-predicate.js:12:31)
lerna ERR!     at packages.forEach (/Users/ovca/Code/GitHub/lerna/utils/collect-updates/collect-updates.js:52:50)
lerna ERR!     at Map.forEach (<anonymous>)
lerna ERR!     at collectUpdates (/Users/ovca/Code/GitHub/lerna/utils/collect-updates/collect-updates.js:51:14)
lerna ERR!     at ChangedCommand.initialize (/Users/ovca/Code/GitHub/lerna/commands/changed/index.js:24:20)
lerna ERR! lerna Command failed: git diff --name-only v1.0.0 --
lerna ERR! lerna fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
lerna ERR! lerna
lerna ERR! lerna
`

because the git diff command is run by lerna as:

`git diff --name-only v1.0.0 -- ''`

resulting in non zero exit code and : `fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`

## Possible Solution

if relative path is empty call git with `'.'` instead of `''`

## Steps to Reproduce (for bugs)

1. `lerna updated`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    ".",
    "packages/*"
  ],
  "version": "0.0.0"
}
```

## Context
I am unable to use lerna as expected if one of the packages is in the root of the lerna project.
## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.2 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | none |
| `node --version` | 8.9.4 |

| OS | Version |
| macOS Sierra | 10.12.3 |

### PR DESCRIPTION
**Pull request by Vunovati**
When location is the same as the cwd, return '.' instead of empty string
otherwise git diff will fail

refs #1322

## Description
Using path.relative is not enough for git params as when comparing two identical paths (`path.relative`) it will return an empty string

## Motivation and Context
Fixes #1322

## How Has This Been Tested?
I added a test case and was not able to reproduce it as in #1322 anymore

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: core/git-utils/index.js [hunk 1]
```diff
@@ -134,7 +134,9 @@ function describeTag(ref, opts) {
 }
 
 function diffSinceIn(committish, location, opts) {
-  const formattedLocation = slash(path.relative(opts.cwd, location));
```
Comment (evocateur) [inline core/git-utils/index.js]: I think I'd rather just leave off the `-- <formattedLocation>` args if `formattedLocation` is empty. The git command works the same way in that case.

```diff
diff --git a/core/git-utils/index.js b/core/git-utils/index.js
index bb11df0f..720ae11a 100644
--- a/core/git-utils/index.js
+++ b/core/git-utils/index.js
@@ -134,15 +134,17 @@ function describeTag(ref, opts) {
 }
 
 function diffSinceIn(committish, location, opts) {
+  const args = ["diff", "--name-only", committish];
   const formattedLocation = slash(path.relative(opts.cwd, location));
 
+  if (formattedLocation) {
+    // avoid same-directory path.relative() === ""
+    args.push("--", formattedLocation);
+  }
+
   log.silly("diffSinceIn", committish, formattedLocation);
 
-  const diff = ChildProcessUtilities.execSync(
-    "git",
-    ["diff", "--name-only", committish, "--", formattedLocation],
-    opts
-  );
+  const diff = ChildProcessUtilities.execSync("git", args, opts);
   log.silly("diff", diff);
 
   return diff;
```

File: core/git-utils/__tests__/git-utils.test.js [hunk 2]
```diff
@@ -259,6 +259,21 @@ describe("GitUtilities", () => {
         opts
       );
     });
+
+    it("returns list of files changed since commit at location when location equals cwd", () => {
```
Comment (evocateur) [inline core/git-utils/__tests__/git-utils.test.js]: I appreciate the test!

**Comment by evocateur** [comment]
@Vunovati Thanks for the fix!

**Comment by Vunovati** [comment]
@evocateur do you know when we can expect a new beta release containing the fix?

I cannot reference it as a git or github dev dependency ("lerna": lerna/lerna#master") in my package.json due to this repo's project structure which prevents it from being installed that way. I  can't think of any other options. Also, Thank you for merging this.

**Comment by evocateur** [comment]
@Vunovati Sorry, meant to release it yesterday. Just published `v3.0.0-beta.3`, thanks again for the contribution!
