### PR TITLE
Fix bootstrap install to use quotes around versions

### LINKED ISSUE #234: Bootstrap doesn't support different ways to specify package version
If I depend on a package like this:

```js
"package": "^1.0.0 || ^2.0.0"
```

The command that gets run is:

```sh
$ npm install package@^1.0.0 || ^2.0.0 ...
```

Which is only installing `package@^1.0.0` and everything after the `||` doesn't get installed

### PR DESCRIPTION
**Pull request by thejameskyle**
Fixes #234

### CODE REVIEW

File: src/commands/BootstrapCommand.js [hunk 1]
```diff
@@ -109,7 +109,7 @@ export default class BootstrapCommand extends Command {
         return !this.hasDependencyInstalled(pkg, dependency);
       })
       .map(dependency => {
-        return dependency + "@" + allDependencies[dependency];
+        return dependency + "@\"" + allDependencies[dependency] + "\"";
```
Comment (gigabo) [inline src/commands/BootstrapCommand.js]: This is getting into the range where a template string might be more readable:

```javascript
return `${dependency}@"${allDependencies[dependency]}"`;
```

Comment (rygine) [inline src/commands/BootstrapCommand.js]: @gigabo i concur

Comment (hzoo) [inline src/commands/BootstrapCommand.js]: Could leave a comment of an example package version of why it needs the quotes
